name: Build & Deploy Spring Library

on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    name: Build and Deploy Spring App First Time
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4