name: Build & Deploy Spring Library

on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    name: Build and Deploy Spring App First Time
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution:  'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file Mateus_Academia/Biblioteca_Virtual/pom.xml

      - name: Build the Application
        run: |
          mvn -B package --file Mateus_Academia/Biblioteca_Virtual/pom.xml


